Repository ExpressLRS/Backpack, pull requests merged in 2024-08, with the labels that each got.

#96 Enhance the OSD test program
  python/osd_test.py
  src/Vrx_main.cpp
Labels: enhancement, V1.5 :cake:

#146 Fix wifi flashing
  python/upload_via_esp8266_backpack.py
Labels: bugfix, V1.5 :cake:

#143 Upgrade dependencies
  lib/WIFI/devWIFI.cpp
  src/options.cpp
  targets/common.ini
  targets/debug.ini
Labels: house keeping :broom:, V1.5 :cake:

#141 Add MAVLink support to Backpack
  lib/BUTTON/devButton.cpp
  lib/MAVLink/MAVLink.cpp
  lib/MAVLink/MAVLink.h
  lib/WIFI/devWIFI.cpp
  lib/config/config.cpp
  lib/config/config.h
  src/Timer_main.cpp
  src/Tx_main.cpp
  src/Vrx_main.cpp
  src/module_base.cpp
  targets/common.ini
  targets/txbp_esp.ini
Labels: enhancement, V1.5 :cake:

#147 Add missing targets
  hardware/targets.json
Labels: house keeping :broom:, V1.5 :cake:

#149 Fix the firmware file for the HDZero goggles
  hardware/targets.json
Labels: bugfix, V1.5 :cake:

#151 Remove "zip" type from targets file
  hardware/targets.json
Labels: bugfix, V1.5 :cake:

#154 Re-architect mavlink UDP forwarder
  html/log.html
  html/log.js
  lib/MAVLink/MAVLink.cpp
  lib/MAVLink/MAVLink.h
  lib/MSP/msptypes.h
  lib/WIFI/devWIFI.cpp
  lib/config/config.cpp
  lib/config/config.h
  python/build_html.py
  src/Tx_main.cpp
Labels: V1.5 :cake:

#156 gzip 8266 firmware for wifi/upload flashing
  python/binary_configurator.py
Labels: V1.5 :cake:
